# Generated by Django 5.2.4 on 2025-07-26 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.stocktransaction')),
            ],
        ),
    ]
